# Generated by Django 3.2.7 on 2023-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_buyer_producat_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
